[Distribution]
Distribution=ubuntu
Release=26.04
# Universe is required for helix, zellij, btop on Ubuntu.
Repositories=main,universe

[Output]
ImageId=csi-ubuntu-base

[Content]
Packages=
        linux-image-generic
        systemd-boot
        # ubuntu-specific names for shared bundles (same as Debian)
        build-essential
        dnsutils
        mtr-tiny
        ovmf
        pkg-config
        qemu-system-x86
        qemu-utils
