[Distribution]
Distribution=debian
Release=trixie

[Output]
ImageId=csi-debian-base

[Content]
Packages=
        linux-image-amd64
        systemd-boot
        # debian-specific names for the shared bundles
        build-essential
        dnsutils
        mtr-tiny
        ovmf
        pkg-config
        qemu-system-x86
        qemu-utils
