#!/usr/bin/env bash
# nosi/provision/steps/28-ssh-config.sh
#
# Make sshd ready for login on every flavor: drop a config snippet and
# make sure the daemon is enabled (so it comes up on the next boot of a
# flashed image, and right away on a re-run on a live VM).
#
# /etc/ssh/sshd_config.d/00-nosi.conf, two settings:
#   PasswordAuthentication yes
#       Fedora's sshd_config ships with PasswordAuthentication=no by
#       default, which makes the baked `odus:odus.321` credentials
#       useless without an SSH key. Debian / Ubuntu cloud images ship
#       with it on; the drop-in is redundant there but harmless.
#   PermitRootLogin no
#       Defense in depth on top of step 22's `passwd -l root` (cloud-init
#       runcmd). If something rotates the root password later, sshd
#       still won't accept root logins.
#
# Enablement: openssh-server's postinst enables ssh.service on
# Debian/Ubuntu, and Fedora Cloud enables sshd.service via preset, so in
# practice the daemon is already on. We enable it explicitly anyway so
# the "ready for login" guarantee does not depend on those defaults (and
# survives a minimal base or an accidental mask). Unit name differs:
# `ssh` on Debian/Ubuntu, `sshd` on Fedora. Host keys are stripped at the
# end of the bake and regenerated by cloud-init on first boot, so a
# flashed image has a per-instance identity before sshd accepts logins.
#
# Idempotency: nosi_write_if_changed only touches mtime when the content
# differs; enable/unmask are idempotent.

. "$(dirname "$(readlink -f "$0")")/../lib/common.sh"

nosi_info "step 28-ssh-config"
nosi_require_root

install -d -m 0755 /etc/ssh/sshd_config.d
nosi_write_if_changed \
'# Managed by nosi/provision/steps/28-ssh-config.sh
PasswordAuthentication yes
PermitRootLogin no
' /etc/ssh/sshd_config.d/00-nosi.conf 0644

# Enablement: openssh-server on Debian/Ubuntu ships BOTH ssh.service and
# (more recent versions) ssh.socket; the cloud image may have either enabled
# by default. Walk every candidate, enable each that actually exists, and
# log the resulting state so the bake log makes "is sshd ready for login?"
# answerable without booting the image. Fedora ships sshd.service only.
case "$NOSI_DISTRO" in
fedora) ssh_units=(sshd.service) ;;
*)      ssh_units=(ssh.service ssh.socket) ;;
esac

systemctl daemon-reload 2>/dev/null || true

for u in "${ssh_units[@]}"; do
    if ! systemctl cat "$u" >/dev/null 2>&1; then
        nosi_info "$u not present on this system; skipping"
        continue
    fi
    if ! systemctl unmask "$u" 2>/dev/null; then
        nosi_warn "unmask $u failed"
    fi
    if systemctl enable "$u" 2>/dev/null; then
        nosi_info "enabled $u"
    else
        nosi_warn "enable $u failed"
    fi
done

# On a live system (Hetzner-VM re-run), pick up the new drop-in now. No-op
# at bake time when systemd isn't running for that unit.
for u in "${ssh_units[@]}"; do
    if systemctl is-active --quiet "$u" 2>/dev/null; then
        systemctl reload "$u" 2>/dev/null \
            || systemctl try-restart "$u" 2>/dev/null \
            || nosi_warn "reload/restart $u failed"
    fi
done

# Final visible state. Surfaces in the bake log as e.g.
#   [nosi] ssh.service is-enabled: enabled
#   [nosi] ssh.socket  is-enabled: disabled
# so we can tell from the log alone whether the next boot will start sshd.
for u in "${ssh_units[@]}"; do
    if systemctl cat "$u" >/dev/null 2>&1; then
        state="$(systemctl is-enabled "$u" 2>/dev/null || echo unknown)"
        nosi_info "$u is-enabled: $state"
    fi
done

nosi_info "step 28-ssh-config done"
