#!/usr/bin/env bash
# nosi/provision/steps/28-ssh-config.sh
#
# Make sshd ready for login on every flavor: drop a config snippet and
# make sure the daemon is enabled (so it comes up on the next boot of a
# flashed image, and right away on a re-run on a live VM).
#
# /etc/ssh/sshd_config.d/00-nosi.conf, two settings:
#   PasswordAuthentication yes
#       Fedora's sshd_config ships with PasswordAuthentication=no by
#       default, which makes the baked `odus:odus.321` credentials
#       useless without an SSH key. Debian / Ubuntu cloud images ship
#       with it on; the drop-in is redundant there but harmless.
#   PermitRootLogin no
#       Defense in depth on top of step 22's `passwd -l root` (cloud-init
#       runcmd). If something rotates the root password later, sshd
#       still won't accept root logins.
#
# Enablement: openssh-server's postinst enables ssh.service on
# Debian/Ubuntu, and Fedora Cloud enables sshd.service via preset, so in
# practice the daemon is already on. We enable it explicitly anyway so
# the "ready for login" guarantee does not depend on those defaults (and
# survives a minimal base or an accidental mask). Unit name differs:
# `ssh` on Debian/Ubuntu, `sshd` on Fedora. Host keys are stripped at the
# end of the bake and regenerated by cloud-init on first boot, so a
# flashed image has a per-instance identity before sshd accepts logins.
#
# Idempotency: nosi_write_if_changed only touches mtime when the content
# differs; enable/unmask are idempotent.

. "$(dirname "$(readlink -f "$0")")/../lib/common.sh"

nosi_info "step 28-ssh-config"
nosi_require_root

install -d -m 0755 /etc/ssh/sshd_config.d
nosi_write_if_changed \
'# Managed by nosi/provision/steps/28-ssh-config.sh
PasswordAuthentication yes
PermitRootLogin no
' /etc/ssh/sshd_config.d/00-nosi.conf 0644

case "$NOSI_DISTRO" in
fedora) ssh_unit=sshd ;;
*)      ssh_unit=ssh ;;
esac

# Enable for next boot regardless of context. unmask first in case a
# prior pass (or a base image) left it masked.
systemctl unmask "${ssh_unit}.service" 2>/dev/null || true
systemctl enable "${ssh_unit}.service" 2>/dev/null || true

# On a live system (Hetzner VM re-run), pick up the new drop-in now.
# Reload is a no-op when the daemon is not running (bake-time chroot /
# WSL without systemd), so this never fails the step.
if systemctl is-active --quiet "${ssh_unit}.service" 2>/dev/null; then
    systemctl reload "${ssh_unit}.service" 2>/dev/null || true
fi

nosi_info "step 28-ssh-config done (sshd enabled via ${ssh_unit}.service)"
