[Distribution]
Distribution=fedora
# Pinning to a specific release keeps builds reproducible; bump as needed.
Release=44

[Output]
ImageId=csi-fedora-base

[Content]
Packages=
        kernel
        systemd-boot-unsigned
        # fedora-specific names for the shared bundles
        bind-utils
        edk2-ovmf
        gcc
        gcc-c++
        mtr
        pkgconf-pkg-config
        qemu-img
        qemu-system-x86-core
